repos:
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black

-   repo: https://gitlab.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        args: [--max-line-length=120]
