name: Black

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Install Black"
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: "Run Black"
        run: |
          python -m black --check --verbose --line-length 120 dynamo tests
