name: Flake8

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Install Flake8"
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: "Run Flake8"
        run: |
          python -m flake8 --config=.flake8 dynamo tests
